# Generated by Django 4.1.9 on 2023-06-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('Job_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Job_Title', models.CharField(max_length=100)),
                ('Job_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('App_ID', models.AutoField(primary_key=True, serialize=False)),
                ('App_Name', models.CharField(max_length=100)),
                ('App_Email', models.EmailField(max_length=254)),
                ('App_Contact', models.CharField(max_length=15)),
                ('Job_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knobeeApp.joblistings')),
            ],
        ),
    ]
