# Generated by Django 4.1.9 on 2023-06-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knobeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='App_Contact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='jobapplications',
            old_name='App_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='jobapplications',
            old_name='App_Name',
            new_name='Name',
        ),
    ]
